### ISSUE TITLE
Descrição do projeto e passos que precisam ser desenvolvidos

### ISSUE THREAD

**Issue by luanlary** [indiqMe/indiqme-web#8]
Acho que poderia ter uma descrição do que o projeto será e de algumas metas para serem desenvolvidas, para podermos começar

**Comment by davifsroberto** [comment]
> Acho que poderia ter uma descrição do que o projeto será e de algumas metas para serem desenvolvidas, para podermos começar

Com certeza @luanlary , em breve iremos disponibilizar... no momento estamos preparando o ambiente para começarmos com uma estrutura legal ;-) assim vai ficar show pra galera meter a mão na massa.

Abraços!

**Comment by luanlary** [comment]
Obrigado @davifsroberto , vou aguardar... estou ancioso por esse projeto man. vlw

**Comment by raffacabofrio** [comment]
@luanlary , alguns links úteis...

Whats: https://chat.whatsapp.com/L9lFpp1nxN0GaP9ppDVi6d

Slack: https://goo.gl/T6CD6H

Trello: https://trello.com/invite/indiqme/d9dbbe074bc5449b741e5f5bfe6798c5
